
import LightDeepak from "@/components/diwali/LightDeepak";
import Glitter from "@/components/diwali/Glitter";
export const metadata = {
  title: "Diwali",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className='bg-gradient-to-br from-yellow-100 via-orange-200 to-white w-screen min-h-screen'>
          
        {children}
      </div>
  );
}
